# Generated by Django 2.2.14 on 2020-07-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200723_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billingpostcode',
            new_name='billingPostcode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingcity',
            new_name='shippingCity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingpostcode',
            new_name='shippingPostcode',
        ),
    ]
